// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type BookRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	CarNo                string   `protobuf:"bytes,3,opt,name=car_no,json=carNo,proto3" json:"car_no,omitempty"`
	ParkNo               string   `protobuf:"bytes,4,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	ParkName             string   `protobuf:"bytes,5,opt,name=park_name,json=parkName,proto3" json:"park_name,omitempty"`
	SpaceId              int64    `protobuf:"varint,6,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	SpaceNo              string   `protobuf:"bytes,7,opt,name=space_no,json=spaceNo,proto3" json:"space_no,omitempty"`
	ChannelId            int64    `protobuf:"varint,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BookRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *BookRequest) GetCarNo() string {
	if m != nil {
		return m.CarNo
	}
	return ""
}

func (m *BookRequest) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *BookRequest) GetParkName() string {
	if m != nil {
		return m.ParkName
	}
	return ""
}

func (m *BookRequest) GetSpaceId() int64 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *BookRequest) GetSpaceNo() string {
	if m != nil {
		return m.SpaceNo
	}
	return ""
}

func (m *BookRequest) GetChannelId() int64 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

type CalFeeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParkNo               string   `protobuf:"bytes,2,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SpaceId              int64    `protobuf:"varint,5,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalFeeRequest) Reset()         { *m = CalFeeRequest{} }
func (m *CalFeeRequest) String() string { return proto.CompactTextString(m) }
func (*CalFeeRequest) ProtoMessage()    {}
func (*CalFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *CalFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalFeeRequest.Unmarshal(m, b)
}
func (m *CalFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalFeeRequest.Marshal(b, m, deterministic)
}
func (m *CalFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalFeeRequest.Merge(m, src)
}
func (m *CalFeeRequest) XXX_Size() int {
	return xxx_messageInfo_CalFeeRequest.Size(m)
}
func (m *CalFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalFeeRequest proto.InternalMessageInfo

func (m *CalFeeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CalFeeRequest) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *CalFeeRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CalFeeRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *CalFeeRequest) GetSpaceId() int64 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

type IDResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDResponse) Reset()         { *m = IDResponse{} }
func (m *IDResponse) String() string { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()    {}
func (*IDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *IDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDResponse.Unmarshal(m, b)
}
func (m *IDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDResponse.Marshal(b, m, deterministic)
}
func (m *IDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDResponse.Merge(m, src)
}
func (m *IDResponse) XXX_Size() int {
	return xxx_messageInfo_IDResponse.Size(m)
}
func (m *IDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IDResponse proto.InternalMessageInfo

func (m *IDResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EnterRequest struct {
	ParkNo               string   `protobuf:"bytes,1,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	CarNo                string   `protobuf:"bytes,2,opt,name=car_no,json=carNo,proto3" json:"car_no,omitempty"`
	LeaveTime            string   `protobuf:"bytes,3,opt,name=leave_time,json=leaveTime,proto3" json:"leave_time,omitempty"`
	ParkingNo            string   `protobuf:"bytes,4,opt,name=parking_no,json=parkingNo,proto3" json:"parking_no,omitempty"`
	ParkingType          string   `protobuf:"bytes,5,opt,name=parking_type,json=parkingType,proto3" json:"parking_type,omitempty"`
	EnterImg             string   `protobuf:"bytes,6,opt,name=enter_img,json=enterImg,proto3" json:"enter_img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRequest) Reset()         { *m = EnterRequest{} }
func (m *EnterRequest) String() string { return proto.CompactTextString(m) }
func (*EnterRequest) ProtoMessage()    {}
func (*EnterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *EnterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRequest.Unmarshal(m, b)
}
func (m *EnterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRequest.Marshal(b, m, deterministic)
}
func (m *EnterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRequest.Merge(m, src)
}
func (m *EnterRequest) XXX_Size() int {
	return xxx_messageInfo_EnterRequest.Size(m)
}
func (m *EnterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRequest proto.InternalMessageInfo

func (m *EnterRequest) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *EnterRequest) GetCarNo() string {
	if m != nil {
		return m.CarNo
	}
	return ""
}

func (m *EnterRequest) GetLeaveTime() string {
	if m != nil {
		return m.LeaveTime
	}
	return ""
}

func (m *EnterRequest) GetParkingNo() string {
	if m != nil {
		return m.ParkingNo
	}
	return ""
}

func (m *EnterRequest) GetParkingType() string {
	if m != nil {
		return m.ParkingType
	}
	return ""
}

func (m *EnterRequest) GetEnterImg() string {
	if m != nil {
		return m.EnterImg
	}
	return ""
}

type EndRequest struct {
	ParkNo               string   `protobuf:"bytes,1,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	CarNo                string   `protobuf:"bytes,2,opt,name=car_no,json=carNo,proto3" json:"car_no,omitempty"`
	LeaveTime            string   `protobuf:"bytes,3,opt,name=leave_time,json=leaveTime,proto3" json:"leave_time,omitempty"`
	ParkingNo            string   `protobuf:"bytes,4,opt,name=parking_no,json=parkingNo,proto3" json:"parking_no,omitempty"`
	LeaveImg             string   `protobuf:"bytes,5,opt,name=leave_img,json=leaveImg,proto3" json:"leave_img,omitempty"`
	ParkingType          string   `protobuf:"bytes,6,opt,name=parking_type,json=parkingType,proto3" json:"parking_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndRequest) Reset()         { *m = EndRequest{} }
func (m *EndRequest) String() string { return proto.CompactTextString(m) }
func (*EndRequest) ProtoMessage()    {}
func (*EndRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *EndRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndRequest.Unmarshal(m, b)
}
func (m *EndRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndRequest.Marshal(b, m, deterministic)
}
func (m *EndRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndRequest.Merge(m, src)
}
func (m *EndRequest) XXX_Size() int {
	return xxx_messageInfo_EndRequest.Size(m)
}
func (m *EndRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndRequest proto.InternalMessageInfo

func (m *EndRequest) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *EndRequest) GetCarNo() string {
	if m != nil {
		return m.CarNo
	}
	return ""
}

func (m *EndRequest) GetLeaveTime() string {
	if m != nil {
		return m.LeaveTime
	}
	return ""
}

func (m *EndRequest) GetParkingNo() string {
	if m != nil {
		return m.ParkingNo
	}
	return ""
}

func (m *EndRequest) GetLeaveImg() string {
	if m != nil {
		return m.LeaveImg
	}
	return ""
}

func (m *EndRequest) GetParkingType() string {
	if m != nil {
		return m.ParkingType
	}
	return ""
}

type SimpleResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type OrderResponse struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile               string     `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	CarNo                string     `protobuf:"bytes,4,opt,name=car_no,json=carNo,proto3" json:"car_no,omitempty"`
	ParkNo               string     `protobuf:"bytes,5,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	ParkName             string     `protobuf:"bytes,6,opt,name=park_name,json=parkName,proto3" json:"park_name,omitempty"`
	SpaceId              int64      `protobuf:"varint,7,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	SpaceNo              string     `protobuf:"bytes,8,opt,name=space_no,json=spaceNo,proto3" json:"space_no,omitempty"`
	Status               int32      `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32      `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	PaymentType          int32      `protobuf:"varint,11,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	StartTime            string     `protobuf:"bytes,12,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string     `protobuf:"bytes,13,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalFee             int32      `protobuf:"varint,14,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	DiscountFee          int32      `protobuf:"varint,15,opt,name=discount_fee,json=discountFee,proto3" json:"discount_fee,omitempty"`
	OtherFee             int32      `protobuf:"varint,16,opt,name=other_fee,json=otherFee,proto3" json:"other_fee,omitempty"`
	Parkings             []*Parking `protobuf:"bytes,17,rep,name=parkings,proto3" json:"parkings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OrderResponse) GetCarNo() string {
	if m != nil {
		return m.CarNo
	}
	return ""
}

func (m *OrderResponse) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *OrderResponse) GetParkName() string {
	if m != nil {
		return m.ParkName
	}
	return ""
}

func (m *OrderResponse) GetSpaceId() int64 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *OrderResponse) GetSpaceNo() string {
	if m != nil {
		return m.SpaceNo
	}
	return ""
}

func (m *OrderResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderResponse) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *OrderResponse) GetPaymentType() int32 {
	if m != nil {
		return m.PaymentType
	}
	return 0
}

func (m *OrderResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *OrderResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *OrderResponse) GetTotalFee() int32 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *OrderResponse) GetDiscountFee() int32 {
	if m != nil {
		return m.DiscountFee
	}
	return 0
}

func (m *OrderResponse) GetOtherFee() int32 {
	if m != nil {
		return m.OtherFee
	}
	return 0
}

func (m *OrderResponse) GetParkings() []*Parking {
	if m != nil {
		return m.Parkings
	}
	return nil
}

type Parking struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	EnterTime            string   `protobuf:"bytes,2,opt,name=enter_time,json=enterTime,proto3" json:"enter_time,omitempty"`
	LeaveTime            string   `protobuf:"bytes,3,opt,name=leave_time,json=leaveTime,proto3" json:"leave_time,omitempty"`
	FreeTo               string   `protobuf:"bytes,4,opt,name=free_to,json=freeTo,proto3" json:"free_to,omitempty"`
	LimitTo              string   `protobuf:"bytes,5,opt,name=limit_to,json=limitTo,proto3" json:"limit_to,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	EnterImg             string   `protobuf:"bytes,7,opt,name=enter_img,json=enterImg,proto3" json:"enter_img,omitempty"`
	LeaveImg             string   `protobuf:"bytes,8,opt,name=leave_img,json=leaveImg,proto3" json:"leave_img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parking) Reset()         { *m = Parking{} }
func (m *Parking) String() string { return proto.CompactTextString(m) }
func (*Parking) ProtoMessage()    {}
func (*Parking) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *Parking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parking.Unmarshal(m, b)
}
func (m *Parking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parking.Marshal(b, m, deterministic)
}
func (m *Parking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parking.Merge(m, src)
}
func (m *Parking) XXX_Size() int {
	return xxx_messageInfo_Parking.Size(m)
}
func (m *Parking) XXX_DiscardUnknown() {
	xxx_messageInfo_Parking.DiscardUnknown(m)
}

var xxx_messageInfo_Parking proto.InternalMessageInfo

func (m *Parking) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Parking) GetEnterTime() string {
	if m != nil {
		return m.EnterTime
	}
	return ""
}

func (m *Parking) GetLeaveTime() string {
	if m != nil {
		return m.LeaveTime
	}
	return ""
}

func (m *Parking) GetFreeTo() string {
	if m != nil {
		return m.FreeTo
	}
	return ""
}

func (m *Parking) GetLimitTo() string {
	if m != nil {
		return m.LimitTo
	}
	return ""
}

func (m *Parking) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Parking) GetEnterImg() string {
	if m != nil {
		return m.EnterImg
	}
	return ""
}

func (m *Parking) GetLeaveImg() string {
	if m != nil {
		return m.LeaveImg
	}
	return ""
}

type SearchRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParkNo               string   `protobuf:"bytes,2,opt,name=park_no,json=parkNo,proto3" json:"park_no,omitempty"`
	SpaceId              int64    `protobuf:"varint,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OrderType            string   `protobuf:"bytes,7,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SearchRequest) GetParkNo() string {
	if m != nil {
		return m.ParkNo
	}
	return ""
}

func (m *SearchRequest) GetSpaceId() int64 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

func (m *SearchRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *SearchRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *SearchRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SearchRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

type SearchResponse struct {
	Total                int32            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Results              []*OrderResponse `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResponse) GetResults() []*OrderResponse {
	if m != nil {
		return m.Results
	}
	return nil
}

type NewSpaceRequest struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	SpaceId              int64    `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSpaceRequest) Reset()         { *m = NewSpaceRequest{} }
func (m *NewSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*NewSpaceRequest) ProtoMessage()    {}
func (*NewSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *NewSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSpaceRequest.Unmarshal(m, b)
}
func (m *NewSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSpaceRequest.Marshal(b, m, deterministic)
}
func (m *NewSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSpaceRequest.Merge(m, src)
}
func (m *NewSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_NewSpaceRequest.Size(m)
}
func (m *NewSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewSpaceRequest proto.InternalMessageInfo

func (m *NewSpaceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewSpaceRequest) GetSpaceId() int64 {
	if m != nil {
		return m.SpaceId
	}
	return 0
}

type PaidRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalFee             int32    `protobuf:"varint,2,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	DiscountFee          int32    `protobuf:"varint,3,opt,name=discount_fee,json=discountFee,proto3" json:"discount_fee,omitempty"`
	OtherFee             int32    `protobuf:"varint,4,opt,name=other_fee,json=otherFee,proto3" json:"other_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaidRequest) Reset()         { *m = PaidRequest{} }
func (m *PaidRequest) String() string { return proto.CompactTextString(m) }
func (*PaidRequest) ProtoMessage()    {}
func (*PaidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *PaidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaidRequest.Unmarshal(m, b)
}
func (m *PaidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaidRequest.Marshal(b, m, deterministic)
}
func (m *PaidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaidRequest.Merge(m, src)
}
func (m *PaidRequest) XXX_Size() int {
	return xxx_messageInfo_PaidRequest.Size(m)
}
func (m *PaidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaidRequest proto.InternalMessageInfo

func (m *PaidRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaidRequest) GetTotalFee() int32 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *PaidRequest) GetDiscountFee() int32 {
	if m != nil {
		return m.DiscountFee
	}
	return 0
}

func (m *PaidRequest) GetOtherFee() int32 {
	if m != nil {
		return m.OtherFee
	}
	return 0
}

func init() {
	proto.RegisterType((*IDRequest)(nil), "pb.IDRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*BookRequest)(nil), "pb.BookRequest")
	proto.RegisterType((*CalFeeRequest)(nil), "pb.CalFeeRequest")
	proto.RegisterType((*IDResponse)(nil), "pb.IDResponse")
	proto.RegisterType((*EnterRequest)(nil), "pb.EnterRequest")
	proto.RegisterType((*EndRequest)(nil), "pb.EndRequest")
	proto.RegisterType((*SimpleResponse)(nil), "pb.SimpleResponse")
	proto.RegisterType((*OrderResponse)(nil), "pb.OrderResponse")
	proto.RegisterType((*Parking)(nil), "pb.Parking")
	proto.RegisterType((*SearchRequest)(nil), "pb.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "pb.SearchResponse")
	proto.RegisterType((*NewSpaceRequest)(nil), "pb.NewSpaceRequest")
	proto.RegisterType((*PaidRequest)(nil), "pb.PaidRequest")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcf, 0x72, 0xe3, 0xc4,
	0x13, 0x8e, 0x24, 0xeb, 0x5f, 0x2b, 0x76, 0x7e, 0x3b, 0xbf, 0x25, 0x2b, 0x62, 0x5c, 0x15, 0x74,
	0x21, 0xb0, 0xe0, 0xaa, 0x5d, 0x8a, 0xe2, 0xc2, 0x85, 0x64, 0xb3, 0x55, 0xbe, 0x98, 0x94, 0x1c,
	0xce, 0xae, 0x89, 0x34, 0x9b, 0xa8, 0x56, 0xd2, 0x08, 0x69, 0x0c, 0x15, 0xde, 0x81, 0x17, 0xa2,
	0x78, 0x05, 0xde, 0x81, 0xe2, 0xc0, 0x8d, 0x77, 0xa0, 0xa6, 0x47, 0xb2, 0x35, 0x78, 0x95, 0xc0,
	0x89, 0x9b, 0xfb, 0xeb, 0x99, 0xd1, 0xd7, 0xdd, 0xdf, 0x37, 0x63, 0x08, 0x78, 0x9d, 0xb2, 0x7a,
	0x5e, 0xd5, 0x5c, 0x70, 0x62, 0x56, 0x37, 0xd1, 0x14, 0xfc, 0xc5, 0xab, 0x98, 0x7d, 0xb7, 0x61,
	0x8d, 0x20, 0x13, 0x30, 0xb3, 0x34, 0x34, 0x4e, 0x8d, 0x33, 0x2b, 0x36, 0xb3, 0x34, 0xfa, 0x12,
	0x46, 0xdf, 0x36, 0xac, 0x26, 0xcf, 0xc0, 0xdd, 0x34, 0xac, 0x5e, 0x6f, 0x93, 0x8e, 0x0c, 0x17,
	0x29, 0x39, 0x06, 0xa7, 0xe0, 0x37, 0x59, 0xce, 0x42, 0xf3, 0xd4, 0x38, 0xf3, 0xe3, 0x36, 0x8a,
	0x7e, 0x33, 0x20, 0x38, 0xe7, 0xfc, 0x6d, 0x77, 0xf0, 0xbf, 0x3d, 0x80, 0xbc, 0x07, 0x4e, 0x42,
	0xeb, 0x75, 0xc9, 0x43, 0x0b, 0x71, 0x3b, 0xa1, 0xf5, 0x92, 0xcb, 0x73, 0x2a, 0x5a, 0xbf, 0x95,
	0xf8, 0x48, 0xad, 0x97, 0xe1, 0x92, 0x93, 0x29, 0xf8, 0x2a, 0x41, 0x0b, 0x16, 0xda, 0x98, 0xf2,
	0x30, 0x45, 0x0b, 0x46, 0xde, 0x07, 0xaf, 0xa9, 0x68, 0xc2, 0xe4, 0xe7, 0x1d, 0xfc, 0xbc, 0x8b,
	0xf1, 0x22, 0xdd, 0xa5, 0x4a, 0x1e, 0xba, 0xb8, 0x4d, 0xa5, 0x96, 0x9c, 0xcc, 0x00, 0x92, 0x3b,
	0x5a, 0x96, 0x2c, 0x97, 0xfb, 0x3c, 0xdc, 0xe7, 0xb7, 0xc8, 0x22, 0x8d, 0x7e, 0x32, 0x60, 0x7c,
	0x41, 0xf3, 0xd7, 0x8c, 0x0d, 0x74, 0xaf, 0x4f, 0xd6, 0xd4, 0xc8, 0xce, 0x00, 0x1a, 0x41, 0x6b,
	0xb1, 0x16, 0x59, 0xc1, 0xb0, 0x40, 0x2b, 0xf6, 0x11, 0xb9, 0xce, 0x14, 0x5d, 0x56, 0xa6, 0x2a,
	0x39, 0x52, 0x74, 0x59, 0x99, 0x76, 0xa9, 0x6d, 0x25, 0xb6, 0x56, 0x49, 0xf4, 0x01, 0x80, 0x1c,
	0x64, 0x53, 0xf1, 0xb2, 0x61, 0x7b, 0x93, 0xfc, 0xc5, 0x80, 0xc3, 0xcb, 0x52, 0xb0, 0xba, 0x37,
	0x91, 0x8e, 0x9c, 0xa1, 0x91, 0xdb, 0x75, 0xde, 0xec, 0x77, 0x7e, 0x06, 0x90, 0x33, 0xfa, 0x3d,
	0xdb, 0x71, 0xf6, 0x63, 0x1f, 0x11, 0x24, 0x36, 0x03, 0x90, 0xfb, 0xb3, 0xf2, 0x76, 0x37, 0x1b,
	0xbf, 0x45, 0x96, 0x9c, 0x7c, 0x08, 0x87, 0x5d, 0x5a, 0xdc, 0x57, 0xdd, 0x84, 0x82, 0x16, 0xbb,
	0xbe, 0xaf, 0x98, 0x9c, 0x20, 0x93, 0x04, 0xd7, 0x59, 0x71, 0x8b, 0x53, 0xf2, 0x63, 0x0f, 0x81,
	0x45, 0x71, 0x1b, 0xfd, 0x6c, 0x00, 0x5c, 0x96, 0xe9, 0x7f, 0x43, 0x7e, 0x0a, 0x6a, 0x2d, 0x32,
	0x6b, 0xb5, 0x85, 0xc0, 0xa2, 0xb8, 0xdd, 0xab, 0xcc, 0xd9, 0xab, 0x2c, 0x3a, 0x83, 0xc9, 0x2a,
	0x2b, 0xaa, 0x9c, 0x6d, 0xa7, 0x73, 0x0c, 0x4e, 0xcd, 0x9a, 0x4d, 0x2e, 0x90, 0xbe, 0x1d, 0xb7,
	0x51, 0xf4, 0xbb, 0x05, 0xe3, 0x6f, 0xa4, 0x41, 0x87, 0xe6, 0xd8, 0x37, 0x92, 0x39, 0x60, 0x24,
	0x6b, 0xc0, 0x48, 0xa3, 0x01, 0x23, 0xd9, 0xc3, 0x46, 0x72, 0x1e, 0x30, 0x92, 0x3b, 0x6c, 0x24,
	0x4f, 0x37, 0xd2, 0x31, 0x38, 0x8d, 0xa0, 0x62, 0xd3, 0x84, 0xbe, 0xaa, 0x56, 0x45, 0x84, 0xc0,
	0x08, 0x5b, 0x06, 0x88, 0xe2, 0x6f, 0xd5, 0xce, 0xfb, 0x82, 0x95, 0x42, 0xb5, 0x33, 0xc0, 0x5c,
	0xd0, 0x62, 0x28, 0x14, 0xdd, 0x3d, 0x87, 0x6a, 0x5a, 0xef, 0x76, 0xcf, 0x58, 0x11, 0xe9, 0xdc,
	0x33, 0x05, 0x5f, 0x70, 0x41, 0xf3, 0xf5, 0x1b, 0xc6, 0xc2, 0x09, 0x9e, 0xec, 0x21, 0xf0, 0x9a,
	0xe1, 0x97, 0xd3, 0xac, 0x49, 0xf8, 0xa6, 0x14, 0x98, 0x3f, 0x52, 0x5f, 0xee, 0x30, 0xb9, 0x64,
	0x0a, 0x3e, 0x17, 0x77, 0xac, 0xc6, 0xfc, 0xff, 0xd4, 0x7e, 0x04, 0x64, 0xf2, 0x23, 0xf0, 0xda,
	0xa1, 0x37, 0xe1, 0x93, 0x53, 0xeb, 0x2c, 0x78, 0x19, 0xcc, 0xab, 0x9b, 0xf9, 0x95, 0xc2, 0xe2,
	0x6d, 0x32, 0xfa, 0xc3, 0x00, 0xb7, 0x45, 0x25, 0x59, 0xbc, 0x90, 0x77, 0x17, 0xa3, 0x8b, 0xf1,
	0x22, 0x95, 0x65, 0x2a, 0x3f, 0x60, 0x25, 0x4a, 0xce, 0xca, 0x21, 0x9d, 0x66, 0x1f, 0x92, 0xf4,
	0x33, 0x70, 0xdf, 0xd4, 0x8c, 0xad, 0xc5, 0xf6, 0xa2, 0x94, 0xe1, 0x35, 0x97, 0x5f, 0xcc, 0xb3,
	0x22, 0x13, 0x32, 0xa3, 0x26, 0xef, 0x62, 0x7c, 0xcd, 0xc9, 0x53, 0xb0, 0xab, 0x3a, 0x4b, 0xba,
	0xb1, 0xab, 0x40, 0xf7, 0xa5, 0xab, 0xfb, 0x52, 0xb7, 0x86, 0xa7, 0x5b, 0x23, 0xfa, 0xd5, 0x80,
	0xf1, 0x8a, 0xd1, 0x3a, 0xb9, 0x7b, 0xf4, 0x19, 0x18, 0xbc, 0x2a, 0xfb, 0x8a, 0xb3, 0x74, 0xc5,
	0xe9, 0x3a, 0x18, 0x3d, 0xa4, 0x03, 0x5b, 0xd7, 0xc1, 0x4e, 0x90, 0xaa, 0xd2, 0x4e, 0x90, 0x33,
	0x00, 0x35, 0x0d, 0x94, 0x9e, 0xaa, 0xd5, 0x47, 0x04, 0x7d, 0xbc, 0x82, 0x49, 0x57, 0x4e, 0xeb,
	0xce, 0xa7, 0x60, 0xa3, 0x7e, 0x5a, 0x1b, 0xab, 0x80, 0x3c, 0x07, 0x57, 0xf9, 0xb9, 0x09, 0x4d,
	0x14, 0xc2, 0x13, 0x29, 0x04, 0xcd, 0xd7, 0x71, 0xb7, 0x22, 0xfa, 0x0a, 0x8e, 0x96, 0xec, 0x87,
	0x95, 0xac, 0x49, 0x7f, 0x47, 0xcc, 0xad, 0xe7, 0xfb, 0x3d, 0x30, 0xf4, 0x4b, 0xff, 0x47, 0x08,
	0xae, 0x68, 0x96, 0x0e, 0xbd, 0x40, 0x9a, 0xe0, 0xcd, 0x47, 0x04, 0x6f, 0x3d, 0x22, 0xf8, 0x91,
	0x2e, 0xf8, 0x97, 0x7f, 0x5a, 0x10, 0x60, 0x51, 0x17, 0x28, 0x07, 0xf2, 0x31, 0x8c, 0xe4, 0x93,
	0x4f, 0x8e, 0x64, 0xb5, 0xbd, 0xc7, 0xff, 0x64, 0x22, 0x81, 0xdd, 0xdb, 0x14, 0x1d, 0x90, 0x17,
	0xe0, 0xa8, 0x4e, 0x12, 0x6c, 0x8d, 0x26, 0x92, 0x13, 0xd2, 0x87, 0xb6, 0x5b, 0x3e, 0x05, 0xe7,
	0x15, 0x13, 0x34, 0xcb, 0xc9, 0xb8, 0x3b, 0x4e, 0x2d, 0xdf, 0x6f, 0x6e, 0x74, 0x40, 0xe6, 0x60,
	0xaf, 0xa4, 0x12, 0xf6, 0xc9, 0xa8, 0xd3, 0xb5, 0xeb, 0x38, 0x3a, 0x20, 0xcf, 0xc1, 0xba, 0x2c,
	0x53, 0x82, 0x4c, 0x77, 0xef, 0xcc, 0xc0, 0xe2, 0xcf, 0xc0, 0xb9, 0xa0, 0x65, 0xc2, 0xf6, 0xa8,
	0xbc, 0x7b, 0xf9, 0x0b, 0xb9, 0x1c, 0x3b, 0x8e, 0x54, 0xb5, 0xff, 0x0c, 0x03, 0x5b, 0xbe, 0x00,
	0xaf, 0x13, 0x05, 0xf9, 0xbf, 0x5c, 0xf1, 0x37, 0x89, 0x0c, 0x12, 0x1b, 0x49, 0x35, 0xa8, 0xa2,
	0x7b, 0xba, 0x18, 0xae, 0xe3, 0xeb, 0xaa, 0x62, 0xf4, 0x9f, 0xd5, 0x71, 0xfe, 0x09, 0x9c, 0x24,
	0xbc, 0x98, 0xd3, 0xac, 0x6e, 0xaf, 0xb2, 0x79, 0x92, 0xf3, 0x4d, 0x3a, 0x47, 0x83, 0x9c, 0x03,
	0x8e, 0xe0, 0x4a, 0xfe, 0xaf, 0xbc, 0x32, 0x6e, 0x1c, 0xfc, 0x83, 0xf9, 0xf9, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x34, 0x63, 0x74, 0x65, 0x6f, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderCenterClient is the client API for OrderCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderCenterClient interface {
	Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*IDResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// rpc UserOrders (User) returns (SearchResponse) {};
	Detail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	Start(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	Cancel(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	CalFee(ctx context.Context, in *CalFeeRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	NewSpace(ctx context.Context, in *NewSpaceRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	Paid(ctx context.Context, in *PaidRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	Appeal(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type orderCenterClient struct {
	cc *grpc.ClientConn
}

func NewOrderCenterClient(cc *grpc.ClientConn) OrderCenterClient {
	return &orderCenterClient{cc}
}

func (c *orderCenterClient) Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Book", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Detail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Start(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/End", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Cancel(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) CalFee(ctx context.Context, in *CalFeeRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/CalFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) NewSpace(ctx context.Context, in *NewSpaceRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/NewSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Paid(ctx context.Context, in *PaidRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Paid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCenterClient) Appeal(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderCenter/Appeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderCenterServer is the server API for OrderCenter service.
type OrderCenterServer interface {
	Book(context.Context, *BookRequest) (*IDResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// rpc UserOrders (User) returns (SearchResponse) {};
	Detail(context.Context, *IDRequest) (*OrderResponse, error)
	Start(context.Context, *BookRequest) (*SimpleResponse, error)
	End(context.Context, *EndRequest) (*SimpleResponse, error)
	Cancel(context.Context, *IDRequest) (*SimpleResponse, error)
	CalFee(context.Context, *CalFeeRequest) (*SimpleResponse, error)
	NewSpace(context.Context, *NewSpaceRequest) (*SimpleResponse, error)
	Paid(context.Context, *PaidRequest) (*SimpleResponse, error)
	Appeal(context.Context, *IDRequest) (*SimpleResponse, error)
}

func RegisterOrderCenterServer(s *grpc.Server, srv OrderCenterServer) {
	s.RegisterService(&_OrderCenter_serviceDesc, srv)
}

func _OrderCenter_Book_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Book(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Book",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Book(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Detail(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Start(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).End(ctx, req.(*EndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Cancel(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_CalFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).CalFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/CalFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).CalFee(ctx, req.(*CalFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_NewSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).NewSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/NewSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).NewSpace(ctx, req.(*NewSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Paid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Paid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Paid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Paid(ctx, req.(*PaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCenter_Appeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCenterServer).Appeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderCenter/Appeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCenterServer).Appeal(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderCenter",
	HandlerType: (*OrderCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Book",
			Handler:    _OrderCenter_Book_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _OrderCenter_Search_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _OrderCenter_Detail_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _OrderCenter_Start_Handler,
		},
		{
			MethodName: "End",
			Handler:    _OrderCenter_End_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _OrderCenter_Cancel_Handler,
		},
		{
			MethodName: "CalFee",
			Handler:    _OrderCenter_CalFee_Handler,
		},
		{
			MethodName: "NewSpace",
			Handler:    _OrderCenter_NewSpace_Handler,
		},
		{
			MethodName: "Paid",
			Handler:    _OrderCenter_Paid_Handler,
		},
		{
			MethodName: "Appeal",
			Handler:    _OrderCenter_Appeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
